build: Update the 'configure' emulation script
Clean up the build tools sanity checks and ensure that we can enable
the API reference generation on demand.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,28 +4,6 @@
 # Copyright 2016 Emmanuele Bassi
 # Licensed under the new-BSD license (http://www.opensource.org/licenses/bsd-license.php)
 
-MESON=$(which meson 2>/dev/null)
-
-if test -z ${MESON}; then
-  echo "*** You must install meson to build this project"
-  exit 1
-fi
-
-# Some distributions rename the Ninja binary to avoid a namespace
-# conflict with another "ninja" application
-NINJA=
-for ninja in "ninja ninja-build"; do
-  ninja_bin=$(which ${ninja} 2>/dev/null)
-  if test -x ${ninja_bin}; then
-    NINJA=${ninja_bin}
-  fi
-done
-
-if test -z ${NINJA}; then
-  echo "*** You must install ninja to build this project"
-  exit 1
-fi
-
 # Little helper function for reading args from the commandline.
 # it automatically handles -a b and -a=b variants, and returns 1 if
 # we need to shift $3.
@@ -44,6 +22,38 @@ read_arg() {
     fi
 }
 
+sanitycheck() {
+    # $1 = arg name
+    # $1 = arg command
+    # $2 = arg alternates
+    local cmd=$( which $2 2>/dev/null )
+
+    if [ -x "$cmd" ]; then
+        read "$1" <<< "$cmd"
+        return 0
+    fi
+
+    test -z $3 || {
+        for alt in $3; do
+            cmd=$( which $alt 2>/dev/null )
+
+            if [ -x "$cmd" ]; then
+                read "$1" <<< "$cmd"
+                return 0
+            fi
+        done
+    }
+
+    echo -e "\e[1;31mERROR\e[0m: Command '$2' not found"
+    exit 1
+}
+
+
+sanitycheck MESON 'meson'
+sanitycheck NINJA 'ninja' 'ninja-build'
+
+enable_docs='-Denable-gtk-doc=false'
+
 while (($# > 0)); do
     case "${1%%=*}" in
 	--prefix) read_arg prefix "$@" || shift;;
@@ -56,6 +66,8 @@ while (($# > 0)); do
 	--libdir) read_arg libdir "$@" || shift;;
 	--mandir) read_arg mandir "$@" || shift;;
 	--includedir) read_arg includedir "$@" || shift;;
+	--enable-gtk-doc) enable_docs='-Denable-gtk-doc=true';;
+	--disable-gtk-doc) enable_docs='-Denable-gtk-doc=false';;
 	*) echo "Ignoring unknown option '$1'";;
     esac
     shift
@@ -110,7 +122,8 @@ exec ${MESON} \
 	--bindir=${bindir} \
 	--includedir=${includedir} \
 	--mandir=${mandir} \
-	-Denable-gtk-doc=false \
+	--default-library shared \
+	${enable_docs} \
 	${srcdir}
 
 # vim: ai ts=8 noet sts=2 ft=sh
